Run tests in deploy script after archiving on Win
It sounds like a good idea to test just built release binaries.

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -125,6 +125,10 @@ if [ "$target" = all -o "$target" = archive ]; then
             echo "ERROR: Building project failed."
             exit 3
         fi
+        if ! RELEASE=1 make -C src/ -f Makefile.win check; then
+            echo "ERROR: Testing project failed."
+            exit 4
+        fi
 
         set -e
 
