Make scripts/release-win build regular Windows zip
This involves:
 1. Pulling tags on the remote side.
 2. Verifying the tag points at the right commit.
 3. Checking out the tag.
 4. Building Windows version remotely.
 5. Checking bitness of binaries just in case.

diff --git a/scripts/release-win b/scripts/release-win
--- a/scripts/release-win
+++ b/scripts/release-win
@@ -46,12 +46,34 @@ W32_DIR="${W32_DIR:-../vifm-mxe-w32/}"
 W64_DIR="${W64_DIR:-../vifm-mxe-w64}"
 MXE_BUILD_SCR="${MXE_BUILD_SCR:-../build-mxe-vifm}"
 
+echo ::: PREPARING WINDOWS REPOSITORY... :::
+
+ssh "$REMOTE_NAME" bash - << EOF
+set -eu
+
+cd "$REMOTE_DIR/"
+if ! git diff --quiet; then
+    echo "Windows repository contains changes.  Aborting."
+    exit 1
+fi
+
+# pull remote tags discarding any conflicting local ones
+git fetch --tags --force
+
+if [ "\$(git rev-parse "$tag")" != "$commit" ]; then
+    echo "Windows repository resolves tag differently.  Aborting."
+    exit 1
+fi
+
+git checkout "$tag"
+EOF
+
 echo ::: BUILDING... :::
 
 ( cd "$W32_DIR" && "$MXE_BUILD_SCR" --32 "$tag" )
 ( cd "$W64_DIR" && "$MXE_BUILD_SCR" --64 "$tag" )
 
-echo ::: CLEANING UP REMOTE DIRECTORIES... :::
+echo ::: PREPARING REMOTE DIRECTORIES... :::
 
 ssh "$REMOTE_NAME" bash - << EOF
 set -eu
@@ -64,6 +86,15 @@ echo ::: COPYING EXECUTABLES TO THE REMOTE... :::
 
 scp "$W32_DIR"/src/*.exe "$REMOTE_NAME:$REMOTE_WIN_DIR/w32/"
 scp "$W64_DIR"/src/*.exe "$REMOTE_NAME:$REMOTE_WIN_DIR/w64/"
+
+echo ::: BUILDING AND PACKAGING WINDOWS VERSION... :::
+
+ssh "$REMOTE_NAME" bash - << EOF
+set -eu
+
+cd "$REMOTE_DIR/"
+scripts/release "$version" archive
+EOF
 
 echo ::: PACKAGING SINGLE-EXECUTABLE VERSIONS... :::
 
@@ -91,14 +122,16 @@ cp w64/*.exe "$w64"
 zip -9 -r "$w64.zip" "$w64"
 EOF
 
-echo ::: COPYING SINGLE-EXECUTABLE VERSIONS LOCALLY... :::
+echo ::: COPYING WINDOWS VERSIONS LOCALLY... :::
 
-scp "$REMOTE_NAME:$REMOTE_WIN_DIR/$w32.zip" \
+scp "$REMOTE_NAME:$REMOTE_WIN_DIR/$win.zip" \
+    "$REMOTE_NAME:$REMOTE_WIN_DIR/$w32.zip" \
     "$REMOTE_NAME:$REMOTE_WIN_DIR/$w64.zip" .
-chmod -x "$w32.zip" "$w64.zip"
+chmod -x "$win.zip" "$w32.zip" "$w64.zip"
 
 echo ::: VERIFYING PACKAGES... :::
 
+unzip "$win.zip"
 unzip "$w32.zip"
 unzip "$w64.zip"
 
@@ -107,6 +140,16 @@ x64_exe='x86-64'
 
 ret=0
 
+if [[ ! "$(file -b "$win/vifm.exe")" =~ "$x32_exe" ]]; then
+    echo "ERROR: Wrong type of $win/vifm.exe:"
+    file -b "$win/vifm.exe"
+    ret=1
+fi
+if [[ ! "$(file -b "$win/win_helper.exe")" =~ "$x32_exe" ]]; then
+    echo "ERROR: Wrong type of $win/win_helper.exe:"
+    file -b "$win/win_helper.exe"
+    ret=1
+fi
 if [[ ! "$(file -b "$w32/vifm.exe")" =~ "$x32_exe" ]]; then
     echo "ERROR: Wrong type of $w32/vifm.exe:"
     file -b "$w32/vifm.exe"
@@ -128,13 +171,13 @@ if [[ ! "$(file -b "$w64/win_helper.exe")" =~ "$x64_exe" ]]; then
     ret=1
 fi
 
-rm -rf "$w32" "$w64"
+rm -rf "$win" "$w32" "$w64"
 
 if [ "$ret" -ne 0 ]; then
     exit "$ret"
 fi
 
-echo ::: COPYING TESTS... :::
+echo ::: COPYING SE TESTS... :::
 
 rm -r "$W32_DIR/tests/bin/build" "$W64_DIR/tests/bin/build"
 
@@ -143,7 +186,7 @@ scp -r "$W32_DIR/tests/bin" "$W32_DIR/tests/test-data" \
 scp -r "$W64_DIR/tests/bin" "$W64_DIR/tests/test-data" \
        "$REMOTE_NAME:$REMOTE_WIN_DIR/w64/"
 
-echo ::: RUNNING TESTS... :::
+echo ::: RUNNING SE TESTS... :::
 
 ssh "$REMOTE_NAME" bash - << EOF
 set -eu
